### ISSUE TITLE
Update nin set fonksiyonu arraylı olsun

### ISSUE THREAD

**Issue by TheYkk** [ismail0234/pdodatabase#11]
sql de update set ederken verileri vidgulle almak yerine 
`set('username','ismail') `
bunun yerine bu

`$arr = [
  'field1' => 'one',
  'field2' => 'two'
];`

olsun
şeklinde almak daha kolay böyle yapsanız daha güzel

**Comment by ismail0234** [comment]
set([
   ['username', '?', 'ismail'],
   ['point', '?', '50'],
])

şeklinde kullanabilirsiniz
