### ISSUE TITLE
Söz dizimi

### ISSUE THREAD

**Issue by TheYkk** [ismail0234/pdodatabase#12]
`$db->set("veri","1")->where("id",$id)->update('tablo')`
bu kullanımda sıra önemsiz olmalı
`$db->update('tablo')->where("id",$id)->set("veri","1")`
böyle kullanınca hata almamalı ama alıyor

**Comment by ismail0234** [comment]
@TheYkk  aldığınız hatayı yazabilirseniz inceleyebiliriz.

**Comment by ismail0234** [comment]
@TheYkk  update fonksiyonu başta kullanılamaz. update artık sorgunuzun hazır oldugunu ve güncelleme işleminin yapılacağını söylemektedir.Bu sebeple update fonksiyonu en sonda yer almalıdır.
