### ISSUE TITLE
ek ozellik

### ISSUE THREAD

**Issue by TheYkk** [ismail0234/pdodatabase#13]
transaction eklerseniz cok guzel olur https://github.com/izniburak/pdox/blob/master/DOCS.md#transaction 
burdaki gibi
bu arada update deki $db->set('point','point - ?',20)->where('id',9)->update('users');
bu kullanim dahice olmus elinize saglik

**Comment by ismail0234** [comment]
yakın zamanda sınıf üzerinde yeni bir revize gelecektir.Transaction bu revize ile eklenecektir.

**Comment by ismail0234** [comment]
v.1.2.7 güncellemesi ile transaction eklenmiştir.
