### ISSUE TITLE
Sql açık

### ISSUE THREAD

**Issue by TheYkk** [ismail0234/pdodatabase#8]

**Comment by ismail0234** [comment]
Bilgi verebilirmisiniz ?

**Comment by TheYkk** [comment]
sql açıklar önlensin direk 
query = $db->from('tablo')->where('id', $_POST['id'])->first();
böyle bir sorgumuz olsun. Burada $_POST['id'] olarak
";TRUNCATE table_name;
böyle bir sorgu gelirse tüm tablo uçmuş olacak.

**Comment by ismail0234** [comment]
Eminmisiniz test ettinizmi ?

**Comment by TheYkk** [comment]
test etmedim şimdi edecem

**Comment by ismail0234** [comment]
Sorun olmayacaktir 2. Deger pdo prepare olarak alinmakta yani string olarak goruluyor

**Comment by ismail0234** [comment]
Son durum nedir bilgilendirebilirmisiniz ?

**Comment by ismail0234** [comment]
dediğiniz yöntemi denedim sql açığı bulunmamakta güvenlik pdo tarafından sağlanmaktadır.
